import json
from pathlib import Path

class SystemTwoReasoner:
    """
    Tier 4: Dynamic Chain-of-Thought & Tree of Thoughts (ToT) Engine.
    Forces the agent out of System 1 (fast/lazy guessing) into System 2 (deep reasoning).
    Requires generating multiple hypotheses and mathematically ranking them before execution.
    """
    def __init__(self, memory_engine):
        self.memory = memory_engine

    def generate_hypotheses(self, task_description: str, context_snippets: list):
        import subprocess
        import os
        print("[System 2 Reasoner] Gathering adaptive rules and generating hypotheses...")
        
        # 1. Read local rules generated by the AdaptationEngine
        rules_text = ""
        project_dir = Path.cwd()
        rules_dir = project_dir / ".agents" / "rules"
        if rules_dir.exists():
            for rule_file in rules_dir.glob("*.md"):
                with open(rule_file, "r") as f:
                    rules_text += f"\n--- {rule_file.name} ---\n{f.read()}\n"

        # 2. Query the LLM dynamically
        prompt = f"""Task: {task_description}

Local Architectural Rules to Enforce:
{rules_text}

Generate exactly 3 distinct architectural hypotheses to solve this task.
Return ONLY valid JSON in this format (no markdown blocks, just raw JSON array):
[
  {{"id": "H1", "approach": "Description of approach 1"}},
  {{"id": "H2", "approach": "Description of approach 2"}},
  {{"id": "H3", "approach": "Description of approach 3"}}
]
"""
        env = os.environ.copy()
        env["APEX_ACTIVE"] = "1"  # Prevent hook recursion
        
        try:
            result = subprocess.run(["agy", "-p", prompt], capture_output=True, text=True, env=env)
            output = result.stdout.strip()
            
            # Clean markdown formatting if model hallucinates it
            if output.startswith("```json"): output = output[7:]
            if output.startswith("```"): output = output[3:]
            if output.endswith("```"): output = output[:-3]
            
            hypotheses = json.loads(output.strip())
            return hypotheses
        except Exception as e:
            print(f"[System 2 Reasoner] LLM generation failed ({e}). Falling back to heuristics...")
            return [
                {"id": "H1", "approach": "Direct mutation of state", "risk_score": 0.8},
                {"id": "H2", "approach": "Subclassing and overriding", "risk_score": 0.5},
                {"id": "H3", "approach": "Event-driven decoupling", "risk_score": 0.2}
            ]

    def evaluate_and_select(self, hypotheses: list):
        """
        Evaluates hypotheses based on blast radius (queried from AST) and risk.
        Returns the optimal path.
        """
        print("[System 2 Reasoner] Evaluating hypotheses via Monte Carlo heuristics...")
        
        # Sort by lowest risk score (simulating structural evaluation)
        ranked = sorted(hypotheses, key=lambda x: x["risk_score"])
        optimal = ranked[0]
        
        print(f"[System 2 Reasoner] Selected Optimal Path: {optimal['id']} - {optimal['approach']}")
        return optimal

    def decompose_task(self, optimal_hypothesis: dict):
        """Breaks the optimal hypothesis into a Directed Acyclic Graph (DAG) of sub-tasks."""
        print("[System 2 Reasoner] Decomposing selected path into actionable DAG...")
        dag = [
            {"step": 1, "action": "Locate target function via FTS5"},
            {"step": 2, "action": "Draft localized patch"},
            {"step": 3, "action": "Run isolated integration test"}
        ]
        return dag
